# Generated by Django 5.2.13 on 2026-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/'),
        ),
    ]
