# Generated by Django 5.2.13 on 2026-04-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_grade_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='courses.course'),
        ),
    ]
